routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.custom_login');
})->name('custom.login');

Route::get('/panduan', 'UtilitiesController@userManual')->name('user.manual');

Auth::routes(['register' => false]);

Route::group(['prefix' => 'password'], function () {
    Route::get('forget', 'PasswordController@showEmailValidation')->name('password.forget');
    Route::post('validate', 'PasswordController@validateUser')->name('password.validate');
    Route::post('reset', 'PasswordController@reset')->name('password.reset');
});

Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    // File and Folder
    Route::group(['namespace' => 'File', 'prefix' => 'manage'], function () {

        Route::group(['prefix' => 'folder'], function () {
            Route::post('create', 'FolderController@createFolder')->name('folder.create');
            Route::post('rename', 'FolderController@rename')->name('folder.rename');
            Route::post('delete', 'FolderController@deleteFolder')->name('folder.delete');
            Route::match(['get', 'post'], 'next', 'FolderController@next')->name('folder.next');
            Route::match(['get', 'post'], 'back', 'FolderController@back')->name('folder.back');
        });

        Route::group(['prefix' => 'file'], function () {
            Route::get('shared', 'FileController@sharedFiles')->name('file.shared');
            Route::get('unit', 'FileController@unitFiles')->name('file.unit');
            // Route::post('upload', 'FileController@upload')->name('file.upload');
            Route::get('download', 'FileController@download')->name('file.download');
            Route::post('rename', 'FileController@rename')->name('file.rename');
            Route::post('delete', 'FileController@delete')->name('file.delete');

            // Route::get('multi-upload', 'FileController@multi')->name('file.multi');
            Route::post('file-multi-upload', 'FileController@multiUpload')->name('file.multi.upload');
            Route::post('update-keterangan', 'FileController@updateKeterangan')->name('file.keterangan.update');
        });

        Route::post('status', 'FileController@changeSharedStatus')->name('status.change');
    });

    // Master Data
    Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function() {
        Route::resource('unit', 'UnitController');
        Route::resource('jabatan', 'JabatanController');
        Route::resource('user', 'UserController');
        Route::get('log', 'LogController@index')->name('log.index');
        Route::get('akses', 'PermissionController@index')->name('akses.index');
        Route::post('akses/update', 'PermissionController@updateAkses')->name('akses.update');

        Route::get('trash', 'TrashController@index')->name('trash.index');
        Route::post('delete-trash/{id}', 'TrashController@permanentDelete')->name('trash.destroy');
        Route::get('cleanup', 'TrashController@cleanUp')->name('trash.cleanup');
    });

    // Global Search
    Route::post('search', 'UtilitiesController@search')->name('search');
    Route::match(['get', 'post'], 'to', 'UtilitiesController@toDestination')->name('toDestination');

    // Change Password
    Route::group(['prefix' => 'setting'], function () {
        Route::get('change-password', 'PasswordController@showChangePasswordForm')->name('password.form');
        Route::post('change', 'PasswordController@change')->name('password.change');
    });

    // get detail
    Route::match(['get', 'post'], 'detail', 'UtilitiesController@detail')->name('file.detail');
});

resources/views/app/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="shortcut icon" href="{{ asset('img/logo.ico') }}" type="image/x-icon">
  <meta name="csrf-token" content="{{ csrf_token() }}">

  <title>Bunda FM</title>

  <!-- Custom fonts for this template-->
  <link href="{{ asset('vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/css/bootstrap-datetimepicker.min.css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{{ asset('css/sb-admin-2.min.css') }}" rel="stylesheet">
  @toastr_css

</head>

<body id="page-top" class="sidebar-togglet">

  <!-- Page Wrapper -->
  <div id="wrapper">
    @include('app.sidebar')

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">
        @include('app.topbar')

        <!-- Begin Page Content -->
        <div class="container-fluid">

          @yield('css')
          @yield('content')
          @yield('js')

        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      @include('app.footer')

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

    <script src="{{ asset('js/app.js') }}"></script>
    <!-- Bootstrap core JavaScript-->
    <script src="{{ asset('vendor/jquery/jquery.min.js') }}"></script>
    <script src="{{ asset('vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{{ asset('vendor/jquery-easing/jquery.easing.min.js') }}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{{ asset('js/sb-admin-2.min.js') }}"></script>
        @toastr_js
        @toastr_render
        @stack('scripts')
    </body>

</html>

resources/views/app/footer.blade.php
<!-- Footer -->
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; File Manager RSIA Puri Bunda (Bunda FM) {{ \Carbon\Carbon::now()->year }}</span>
        </div>
    </div>
</footer>
<!-- End of Footer -->

resources/views/app/sidebar.blade.php
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{ route('home') }}">
      <div class="sidebar-brand-icon">
        {{-- <i class="fas fa-warehouse"></i> --}}
        <img src="{{ asset('img/logo.png') }}" style="width: 30%">
      </div>
      {{-- <div class="sidebar-brand-text mx-3">Bunda FM</div> --}}
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Home
    </div>

    <!-- Nav Item - Dashboard -->
    <li class="nav-item">
      <a class="nav-link" href="{{ route('home') }}">
        <i class="fas fa-fw fa-search"></i>
        {{-- <span>Home</span></a> --}}
        <span>Search</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Nav Item - Pages Collapse Menu -->
    @can('isAdmin')
        <!-- Heading -->
        <div class="sidebar-heading">
            Admin
        </div>

        <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseMasterData" aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-fw fa-cog"></i>
            <span>Master Data</span>
        </a>
        <div id="collapseMasterData" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Kelola Master Data:</h6>
            <a class="collapse-item" href="{{ route('unit.index') }}">Unit</a>
            <a class="collapse-item" href="{{ route('jabatan.index') }}">Jabatan</a>
            <a class="collapse-item" href="{{ route('user.index') }}">User</a>
            <a class="collapse-item" href="{{ route('akses.index') }}">Hak Akses</a>  
            </div>
        </div>
        </li>
    @endcan

    <!-- Heading -->
    <div class="sidebar-heading">
      Manager
    </div>

    <!-- Nav Item - Unit Files -->
    <li class="nav-item">
      <a class="nav-link" href="{{ route('file.unit') }}">
        <i class="fas fa-fw fa-suitcase"></i>
        {{-- <span>{{ Auth::user()->unit->nama_unit }} Files</span></a> --}}
        <span>Unit Files</span></a>
    </li>

    <!-- Nav Item - Shared Files -->
    <li class="nav-item">
      <a class="nav-link" href="{{ route('file.shared') }}">
        <i class="fas fa-fw fa-file"></i>
        <span>Shared Files</span></a>
    </li>

    <!-- Nav Item - Hak Akses User -->
    @if (Auth::user()->isManager && !Auth::user()->isAdmin)
      <li class="nav-item">
        <a class="nav-link" href="{{ route('akses.index') }}">
          <i class="fas fa-fw fa-users-cog"></i>
          <span>Hak Akses User</span></a>
      </li>
    @endif
    
    <!-- Nav Item - User Log -->
    @can('isAdmin')
        <li class="nav-item">
        <a class="nav-link" href="{{ route('trash.index') }}">
            <i class="fas fa-fw fa-recycle"></i>
            <span>Recycle Bin</span></a>
        </li>
    @endcan

    <!-- Nav Item - User Log -->
    @can('isAdmin')
        <li class="nav-item">
        <a class="nav-link" href="{{ route('log.index') }}">
            <i class="fas fa-fw fa-list-alt"></i>
            <span>User Log</span></a>
        </li>
    @endcan

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
      <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

  </ul>
  <!-- End of Sidebar -->

resources/views/app/topbar.blade.php
<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

<!-- Sidebar Toggle (Topbar) -->
<button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
    <i class="fa fa-bars"></i>
</button>

<!-- Topbar Navbar -->
<h5>Bunda FM</h5>

<ul class="navbar-nav ml-auto">

    <div class="topbar-divider d-none d-sm-block"></div>

    <!-- Nav Item - User Information -->
    <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ Auth::user()->nama_user }}</span>
            <i class="fas fa-user-circle"></i>
        </a>
        <!-- Dropdown - User Information -->
        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
            
            @cannot('isAdmin')
                <a class="dropdown-item" href="{{ route('password.form') }}">
                    <i class="fas fa-wrench fa-sm fa-fw mr-2 text-gray-400"></i>
                    Settings
                </a>
            <div class="dropdown-divider"></div>
            @endcannot

            
            <button class="dropdown-item" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                Logout
            </button>
        </div>
    </li>

</ul>
    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
        @csrf
    </form>
</nav>
<!-- End of Topbar -->