routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.custom_login');
})->name('custom.login');

Route::get('/panduan', 'UtilitiesController@userManual')->name('user.manual');

Auth::routes(['register' => false]);

Route::group(['prefix' => 'password'], function () {
    Route::get('forget', 'PasswordController@showEmailValidation')->name('password.forget');
    Route::post('validate', 'PasswordController@validateUser')->name('password.validate');
    Route::post('reset', 'PasswordController@reset')->name('password.reset');
});

Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    // File and Folder
    Route::group(['namespace' => 'File', 'prefix' => 'manage'], function () {

        Route::group(['prefix' => 'folder'], function () {
            Route::post('create', 'FolderController@createFolder')->name('folder.create');
            Route::post('rename', 'FolderController@rename')->name('folder.rename');
            Route::post('delete', 'FolderController@deleteFolder')->name('folder.delete');
            Route::match(['get', 'post'], 'next', 'FolderController@next')->name('folder.next');
            Route::match(['get', 'post'], 'back', 'FolderController@back')->name('folder.back');
        });

        Route::group(['prefix' => 'file'], function () {
            Route::get('shared', 'FileController@sharedFiles')->name('file.shared');
            Route::get('unit', 'FileController@unitFiles')->name('file.unit');
            // Route::post('upload', 'FileController@upload')->name('file.upload');
            Route::get('download', 'FileController@download')->name('file.download');
            Route::post('rename', 'FileController@rename')->name('file.rename');
            Route::post('delete', 'FileController@delete')->name('file.delete');

            // Route::get('multi-upload', 'FileController@multi')->name('file.multi');
            Route::post('file-multi-upload', 'FileController@multiUpload')->name('file.multi.upload');
            Route::post('update-keterangan', 'FileController@updateKeterangan')->name('file.keterangan.update');
        });

        Route::post('status', 'FileController@changeSharedStatus')->name('status.change');
    });

    // Master Data
    Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function() {
        Route::resource('unit', 'UnitController');
        Route::resource('jabatan', 'JabatanController');
        Route::resource('user', 'UserController');
        Route::get('log', 'LogController@index')->name('log.index');
        Route::get('akses', 'PermissionController@index')->name('akses.index');
        Route::post('akses/update', 'PermissionController@updateAkses')->name('akses.update');

        Route::get('trash', 'TrashController@index')->name('trash.index');
        Route::post('delete-trash/{id}', 'TrashController@permanentDelete')->name('trash.destroy');
        Route::get('cleanup', 'TrashController@cleanUp')->name('trash.cleanup');
    });

    // Global Search
    Route::post('search', 'UtilitiesController@search')->name('search');
    Route::match(['get', 'post'], 'to', 'UtilitiesController@toDestination')->name('toDestination');

    // Change Password
    Route::group(['prefix' => 'setting'], function () {
        Route::get('change-password', 'PasswordController@showChangePasswordForm')->name('password.form');
        Route::post('change', 'PasswordController@change')->name('password.change');
    });

    // get detail
    Route::match(['get', 'post'], 'detail', 'UtilitiesController@detail')->name('file.detail');
});

app/Models/Trash.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Trash extends Model
{
    protected $fillable = [
        'nama_unit', 'isFile', 'nama_asli', 'nama_trash', 'latest_path', 'trash_path', 'expired_date', 'isTrashRemovedPermanently'
    ];
}

app/Trash.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Trash extends Model
{
    protected $fillable = [
        'nama_unit', 'isFile', 'nama_asli', 'nama_trash', 'latest_path', 'trash_path', 'expired_date', 'isTrashRemovedPermanently'
    ];
}

app/Http/Controllers/Admin/TrashController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Trash;
use Illuminate\Support\Facades\Storage;
use Carbon\Carbon;

class TrashController extends Controller
{
    public function index()
    {
        $trashes = Trash::where(['isTrashRemovedPermanently' => 0])->orderBy('expired_date')->get();
        return view('admin.trash.index', compact('trashes'));
    }

    public function permanentDelete($id)
    {
        $zipToDelete = Trash::findOrFail($id);
        $zipToDelete->update([
            'isTrashRemovedPermanently' => 1
        ]);

        unlink($zipToDelete->trash_path);
        
        toastr()->success('File sudah dihapus secara permanen!', 'Sukses');
        return redirect()->back();
    }

    public function cleanUp()
    {
        $trashesToDelete = Trash::where(['isTrashRemovedPermanently' => 0])->whereDate('expired_date', '<=', Carbon::now())->get();

        if ($trashesToDelete->count() > 0) {
            foreach ($trashesToDelete as $trash) {
                $trash->update([
                    'isTrashRemovedPermanently' => 1
                ]);
                unlink($trash->trash_path);
            }

            toastr()->success('ZIP kadaluarsa sudah dibersihkan', 'Sukses');
            return redirect()->back();
        } else {
            toastr()->warning('Tidak ada ZIP yang dapat dibersihkan', 'Peringatan');
            return redirect()->back();
        }

    }

    public static function scheduledCleanUp()
    {
        $trashesToDelete = Trash::where(['isTrashRemovedPermanently' => 0])->whereDate('expired_date', '<=', Carbon::now())->get();

        if ($trashesToDelete->count() > 0) {
            foreach ($trashesToDelete as $trash) {
                $trash->update([
                    'isTrashRemovedPermanently' => 1
                ]);
                unlink($trash->trash_path);
            }
        }
    }
}

resources/views/admin/trash/confirm_cleanup_modal.blade.php
<!-- Modal -->
<div class="modal fade" id="changeStatusModal" tabindex="-1" role="dialog" aria-labelledby="changeStatusModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="changeStatusModalTitle">Konfirmasi</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="alert alert-danger" role="alert">
                  <h4 class="alert-heading"> <i class="fas fa-exclamation-triangle"></i> PERINGATAN!</h4>
                  <p>
                    Melakukan Space Clean-Up berarti menghapus semua ZIP file yang sudah expired. Mohon dipastikan apakah anda yakin akan membersihkan ruang ?
                  </p>
                  <hr>
                  <p class="mb-0">File ZIP yang dihapus akan hilang secara permanen dan tidak dapat dikembalikan !</p>
                </div>
            </div>
            <div class="modal-footer d-sm-flex align-items-center justify-content-between">
              <button href="#" class="btn btn-secondary btn-icon-split btn-sm" data-dismiss="modal">
                <span class="icon text-white-50">
                    <i class="fas fa-ban"></i>
                </span>
                <span class="text">Batal</span>
              </button>
              <a href="{{ route('trash.cleanup') }}" class="btn btn-danger btn-icon-split btn-sm">
                <span class="icon text-white-50">
                    <i class="fas fa-bolt"></i>
                </span>
                <span class="text">Hapus Permanen</span>
              </a>
            </div>
        </div>
    </div>
</div>

resources/views/admin/trash/index.blade.php
@extends('app.app')

@section('css')
    {{-- Additional CSS File for this page --}}
    <link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endsection

@section('content')
    <!-- Page Heading -->
    {{-- <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Jabatan</h1>
        <a href="{{ route('jabatan.create') }}" class="btn btn-primary btn-icon-split">
            <span class="icon text-white-50">
                <i class="fas fa-plus-circle"></i>
            </span>
            <span class="text">Tambah Jabatan</span>
        </a>
    </div> --}}

    <!-- DataTables -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <div class="d-sm-flex align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">ZIP Files</h6>
                    {{-- <a href="{{ route('trash.cleanup') }}" class="btn btn-dark btn-icon-split btn-sm"> --}}
                    <button onclick="changeStatusModal()" class="btn btn-dark btn-icon-split btn-sm">
                    <span class="icon text-white-50">
                        <i class="fas fa-bolt"></i>
                    </span>
                    <span class="text">Clean-Up Space</span>
                </a>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
            <table class="table table-sm table-bordered table-hover" id="dataTable" width="100%" cellspacing="0">
                <thead>
                <tr>
                    <th>No</th>
                    <th>Nama Unit</th>
                    <th>Tipe</th>
                    <th>Nama ZIP File</th>
                    <th>Expired Date</th>
                    <th>Status Expired</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @php
                    $no = 1;
                @endphp
                @foreach ($trashes as $trash)
                    <tr>
                        <td>{{ $no++ }}</td>
                        <td>{{ $trash->nama_unit }}</td>
                        <td>{{ $trash->isFile ? 'File' : 'Folder' }}</td>
                        <td>{{ $trash->nama_trash }}</td>
                        <td>{{ $trash->expired_date }}</td>
                        <td>
                            @if (ContentType::isExpired($trash->expired_date))
                                <span class="badge badge-danger">Expired</span>
                            @else
                                <span class="badge badge-success">Available</span>
                            @endif
                        </td>
                        <td>
                            <button class="btn btn-sm btn-danger btn-icon-split" type="submit" onclick="confirmPermanentDelete(event, {{ $trash }})">
                                <span class="icon text-white-50">
                                    <i class="fas fa-trash"></i>
                                </span>
                                <span class="text">
                                    Delete Permanen
                                </span>
                            </button>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            <form action="" id="formDeletePermanen" method="post" style="display: none;">
                @csrf
            </form>
            </div>
        </div>
    </div>

    @include('admin.trash.confirm_cleanup_modal')

    <script>
        function confirmPermanentDelete (event, trash) {
            var urlDeleteTrash = '{{ route("trash.destroy", ":id") }}'
            urlDeleteTrash = urlDeleteTrash.replace(':id', trash.id)

            Swal.fire({
                title: 'Hapus ZIP ini ?',
                text: "Arsip ini akan dihapus secara permanen. Lanjutkan?",
                type: 'question',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                cancelButtonText: 'Batal',
                confirmButtonText: 'Hapus'
                }).then((result) => {
                if (result.value) {
                    event.preventDefault()
                    $('#formDeletePermanen').attr('action', urlDeleteTrash).submit()
                }
            })
        }

        function changeStatusModal() {
            $('#changeStatusModal').modal('show')
        }
    </script>
@endsection

@push('scripts')
    {{-- Additional JS File for this page --}}
    <!-- Page level plugins -->
    <script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>

    <!-- Page level custom scripts -->
    <script src="{{ asset('js/demo/datatables-demo.js') }}"></script>
@endpush