routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.custom_login');
})->name('custom.login');

Route::get('/panduan', 'UtilitiesController@userManual')->name('user.manual');

Auth::routes(['register' => false]);

Route::group(['prefix' => 'password'], function () {
    Route::get('forget', 'PasswordController@showEmailValidation')->name('password.forget');
    Route::post('validate', 'PasswordController@validateUser')->name('password.validate');
    Route::post('reset', 'PasswordController@reset')->name('password.reset');
});

Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    // File and Folder
    Route::group(['namespace' => 'File', 'prefix' => 'manage'], function () {

        Route::group(['prefix' => 'folder'], function () {
            Route::post('create', 'FolderController@createFolder')->name('folder.create');
            Route::post('rename', 'FolderController@rename')->name('folder.rename');
            Route::post('delete', 'FolderController@deleteFolder')->name('folder.delete');
            Route::match(['get', 'post'], 'next', 'FolderController@next')->name('folder.next');
            Route::match(['get', 'post'], 'back', 'FolderController@back')->name('folder.back');
        });

        Route::group(['prefix' => 'file'], function () {
            Route::get('shared', 'FileController@sharedFiles')->name('file.shared');
            Route::get('unit', 'FileController@unitFiles')->name('file.unit');
            // Route::post('upload', 'FileController@upload')->name('file.upload');
            Route::get('download', 'FileController@download')->name('file.download');
            Route::post('rename', 'FileController@rename')->name('file.rename');
            Route::post('delete', 'FileController@delete')->name('file.delete');

            // Route::get('multi-upload', 'FileController@multi')->name('file.multi');
            Route::post('file-multi-upload', 'FileController@multiUpload')->name('file.multi.upload');
            Route::post('update-keterangan', 'FileController@updateKeterangan')->name('file.keterangan.update');
        });

        Route::post('status', 'FileController@changeSharedStatus')->name('status.change');
    });

    // Master Data
    Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function() {
        Route::resource('unit', 'UnitController');
        Route::resource('jabatan', 'JabatanController');
        Route::resource('user', 'UserController');
        Route::get('log', 'LogController@index')->name('log.index');
        Route::get('akses', 'PermissionController@index')->name('akses.index');
        Route::post('akses/update', 'PermissionController@updateAkses')->name('akses.update');

        Route::get('trash', 'TrashController@index')->name('trash.index');
        Route::post('delete-trash/{id}', 'TrashController@permanentDelete')->name('trash.destroy');
        Route::get('cleanup', 'TrashController@cleanUp')->name('trash.cleanup');
    });

    // Global Search
    Route::post('search', 'UtilitiesController@search')->name('search');
    Route::match(['get', 'post'], 'to', 'UtilitiesController@toDestination')->name('toDestination');

    // Change Password
    Route::group(['prefix' => 'setting'], function () {
        Route::get('change-password', 'PasswordController@showChangePasswordForm')->name('password.form');
        Route::post('change', 'PasswordController@change')->name('password.change');
    });

    // get detail
    Route::match(['get', 'post'], 'detail', 'UtilitiesController@detail')->name('file.detail');
});

app/Models/Unit.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Unit extends Model
{
    protected $fillable = [
        'nama_unit', 'nama_folder', 'kapasitas', 'isDireksi', 'status'
    ];

    public function users()
    {
        return $this->hasMany(User::class);
    }

    public function files()
    {
        return $this->hasMany(FileMetaData::class);
    }

    public function folders()
    {
        return $this->hasMany(Folder::class);
    }
}

app/Unit.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Unit extends Model
{
    protected $fillable = [
        'nama_unit', 'nama_folder', 'kapasitas', 'isDireksi', 'status'
    ];

    public function users()
    {
        return $this->hasMany(User::class);
    }

    public function files()
    {
        return $this->hasMany(FileMetaData::class);
    }

    public function folders()
    {
        return $this->hasMany(Folder::class);
    }
}

app/Http/Controllers/Admin/UnitController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Unit;
use App\Http\Requests\UnitRequest;
use App\Helpers\SizeConverter;
use Illuminate\Support\Facades\Storage;
use App\Folder;

class UnitController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $dataUnit = Unit::latest()->where('nama_unit', '!=', 'Administrator')->get();
        return view('admin.unit.index', compact('dataUnit'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.unit.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UnitRequest $request)
    {
        // dd($request->all());
        // Make root folder each unit
        $folderPath = storage_path('app/public/'.$request->nama_folder);
        $relativePath = 'public/'.$request->nama_folder;

        if (!is_dir($folderPath)) {
            Storage::makeDirectory('public/'.$request->nama_folder);

            $convertedKapasitasToBytes = SizeConverter::fromGigaToBytes($request->kapasitas);
            $request->merge(['kapasitas'  => $convertedKapasitasToBytes]);
            $unit = Unit::create($request->all());

            Folder::create([
                'id_unit' => $unit->id,
                'nama_folder' => $request->nama_folder,
                'path' => $relativePath,
                'root' => 1,
                'isPrivate' => 0
            ]);

            toastr()->success('Unit '.$unit->nama_unit.' telah ditambahkan!', 'Sukses');
            return redirect(route('unit.index'));
        } else {
            toastr()->error('Nama folder sudah digunakan!', 'Error');
            return redirect()->back();
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $unit = Unit::findOrFail($id);
        return view('admin.unit.edit', compact('unit'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UnitRequest $request, $id)
    {
        $convertedKapasitasToBytes = SizeConverter::fromGigaToBytes($request->kapasitas);

        $request->merge(['kapasitas'  => $convertedKapasitasToBytes]);
        $unit = Unit::findOrFail($id)->update($request->all());
        toastr()->success('Unit telah diperbarui!', 'Sukses');
        return redirect(route('unit.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $unit = Unit::findOrFail($id);
        $unit->delete();
        
        toastr()->success('Unit '.$unit->nama_unit.' telah dihapus!', 'Sukses');
        return redirect(route('unit.index'));
    }
}

resources/views/admin/unit/create.blade.php
@extends('app.app')

@section('css')
    {{-- Additional CSS for this page --}}
@endsection

@section('content')
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Tambah Unit</h1>
    </div>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Unit Baru</h6>
        </div>
        <div class="card-body">
            <form action="{{ route('unit.store') }}" method="POST">
                @csrf
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label for="namaUnit">Nama Unit</label>
                        <input type="text" value="{{ old('nama_unit') }}" class="form-control" id="namaUnit" name="nama_unit" placeholder="Unit">
                    </div>
                    <div class="form-group col-md-4">
                        <label for="namaFolder">Nama Folder</label>
                        <input type="text" value="{{ old('nama_folder') }}" class="form-control" id="namaFolder" name="nama_folder" placeholder="Folder">                        
                    </div>
                    <div class="form-group col-md-4">
                        <label for="kapasitas">Kapasitas (GB)</label>
                        <input type="number" value="{{ old('nama_folder') }}" class="form-control" id="kapasitas" name="kapasitas">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-inline">
                            <label for="" class="mr-2">Status :</label>
                            <div class="custom-control custom-radio mr-2">
                                <input type="radio" id="inputStatusAktif" value="1" name="status" class="custom-control-input">
                                <label class="custom-control-label" for="inputStatusAktif">Aktif</label>
                            </div>
                            <div class="custom-control custom-radio mr-2">
                                <input type="radio" id="inputStatusNonAktif" value="0" name="status" class="custom-control-input">
                                <label class="custom-control-label" for="inputStatusNonAktif">Tidak Aktif</label>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-inline">
                            <label for="" class="mr-2">Khusus Direksi :</label>
                            <div class="custom-control custom-radio mr-2">
                                <input type="radio" id="inputIsDireksi" value="1" name="isDireksi" class="custom-control-input">
                                <label class="custom-control-label" for="inputIsDireksi">Iya</label>
                            </div>
                            <div class="custom-control custom-radio mr-2">
                                <input type="radio" id="inputIsNotDireksi" value="0" name="isDireksi" class="custom-control-input">
                                <label class="custom-control-label" for="inputIsNotDireksi">Tidak</label>
                            </div>
                        </div>
                    </div>
                </div>
                <button type="submit" href="#" class="btn btn-primary btn-icon-split mt-2">
                    <span class="icon text-white-50">
                        <i class="fas fa-save"></i>
                    </span>
                    <span class="text">Simpan</span>
                </button>
            </form>
        </div>
    </div>
    @php
    if ($errors->any()) {
        foreach ($errors->all() as $message)
        {
            toastr()->error($message, 'Error');
        }
    }
    @endphp
@endsection

@push('js')
    {{-- Additional JS for this page --}}
@endpush

resources/views/admin/unit/edit.blade.php
@extends('app.app')

@section('css')
    {{-- Additional CSS for this page --}}
@endsection

@section('content')
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Edit Unit</h1>
    </div>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Perbarui Unit</h6>
        </div>
        <div class="card-body">
            <form action="{{ route('unit.update', $unit->id) }}" method="POST">
                @csrf
                @method('PUT')
                <input type="hidden" value="{{ $unit->id }}" name="id">
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label for="namaUnit">Nama Unit</label>
                        <input type="text" value="{{ $unit->nama_unit }}" class="form-control" id="namaUnit" name="nama_unit" placeholder="Unit">
                    </div>
                    <div class="form-group col-md-4">
                        <label for="namaFolder">Nama Folder</label>
                        <input type="text" readonly value="{{ $unit->nama_folder }}" class="form-control" id="namaFolder" name="nama_folder" placeholder="Folder">                        
                    </div>
                    <div class="form-group col-md-4">
                        <label for="kapasitas">Kapasitas (GB)</label>
                        <input type="number" value="{{ SizeConverter::fromBytesToGiga($unit->kapasitas) }}" class="form-control" id="kapasitas" name="kapasitas">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-inline">
                            <label for="" class="mr-2">Status :</label>
                            <div class="custom-control custom-radio mr-2">
                                <input type="radio" id="inputStatusAktif" {{ $unit->status == 1 ? 'checked' : '' }} value="1" name="status" class="custom-control-input">
                                <label class="custom-control-label" for="inputStatusAktif">Aktif</label>
                            </div>
                            <div class="custom-control custom-radio mr-2">
                                <input type="radio" id="inputStatusNonAktif" {{ $unit->status == 0 ? 'checked' : '' }} value="0" name="status" class="custom-control-input">
                                <label class="custom-control-label" for="inputStatusNonAktif">Tidak Aktif</label>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-inline">
                            <label for="" class="mr-2">Khusus Direksi :</label>
                            <div class="custom-control custom-radio mr-2">
                                <input type="radio" id="inputIsDireksi" {{ $unit->isDireksi == 1 ? 'checked' : '' }} value="1" name="isDireksi" class="custom-control-input">
                                <label class="custom-control-label" for="inputIsDireksi">Iya</label>
                            </div>
                            <div class="custom-control custom-radio mr-2">
                                <input type="radio" id="inputIsNotDireksi" {{ $unit->isDireksi == 0 ? 'checked' : '' }} value="0" name="isDireksi" class="custom-control-input">
                                <label class="custom-control-label" for="inputIsNotDireksi">Tidak</label>
                            </div>
                        </div>
                    </div>
                </div>
                <button type="submit" href="#" class="btn btn-primary btn-icon-split mt-2">
                    <span class="icon text-white-50">
                        <i class="fas fa-save"></i>
                    </span>
                    <span class="text">Perbarui</span>
                </button>
            </form>
        </div>
    </div>
    @php
    if ($errors->any()) {
        foreach ($errors->all() as $message)
        {
            toastr()->error($message, 'Error');
        }
    }
    @endphp
@endsection

@push('js')
    {{-- Additional JS for this page --}}
@endpush

resources/views/admin/unit/index.blade.php
@extends('app.app')

@section('css')
    {{-- Additional CSS File for this page --}}
    <link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endsection

@section('content')
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Unit</h1>
        <a href="{{ route('unit.create') }}" class="btn btn-primary btn-icon-split">
            <span class="icon text-white-50">
                <i class="fas fa-plus-circle"></i>
            </span>
            <span class="text">Tambah Unit</span>
        </a>
    </div>

    <!-- DataTables -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Master Data Unit</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
            <table class="table table-sm table-bordered table-hover" id="dataTable" width="100%" cellspacing="0">
                <thead>
                <tr>
                    <th>No</th>
                    <th>Nama Unit</th>
                    <th>Root Folder</th>
                    <th>Kapasitas (GB)</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @php
                    $no = 1;
                @endphp
                @foreach ($dataUnit as $unit)
                    <tr>
                        <td>{{ $no++ }}</td>
                        <td>{{ $unit->nama_unit }}</td>
                        <td>{{ $unit->nama_folder }}</td>
                        <td>{{ SizeConverter::fromBytesToGiga($unit->kapasitas) }}</td>
                        <td>
                            <a href="{{ route('unit.edit', $unit->id) }}" class="btn btn-sm btn-success btn-icon-split">
                                <span class="icon text-white-50">
                                    <i class="fas fa-pen-alt"></i>
                                </span>
                                <span class="text">Edit</span>
                            </a>
                            <button class="btn btn-sm btn-danger btn-icon-split" type="submit" onclick="confirmDelete(event, {{ $unit }})">
                                <span class="icon text-white-50">
                                    <i class="fas fa-trash"></i>
                                </span>
                                <span class="text">
                                    Delete
                                </span>
                            </button>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            <form action="" id="formDeleteUnit" method="post" style="display: none;">
                @csrf
                @method('DELETE')
            </form>
            </div>
        </div>
    </div>
    <script>
        function confirmDelete (event, unit) {
            var urlDeleteUnit = '{{ route("unit.destroy", ":id") }}'
            urlDeleteUnit = urlDeleteUnit.replace(':id', unit.id)

            Swal.fire({
                title: 'Hapus unit '+unit.nama_unit+' ?',
                text: "Unit yang dihapus tidak dapat dikembalikan!",
                type: 'question',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                cancelButtonText: 'Batal',
                confirmButtonText: 'Hapus'
                }).then((result) => {
                if (result.value) {
                    event.preventDefault()
                    $('#formDeleteUnit').attr('action', urlDeleteUnit).submit()                
                }
            })
        }
    </script>
@endsection

@push('scripts')
    {{-- Additional JS File for this page --}}
    <!-- Page level plugins -->
    <script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>

    <!-- Page level custom scripts -->
    <script src="{{ asset('js/demo/datatables-demo.js') }}"></script>
@endpush